apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.fastapi_image.image }}:{{ .Values.fastapi_image.tag }}
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}-deployment
  minReplicas: {{ .Values.fastapi_hpa.minReplicas }}
  maxReplicas: {{ .Values.fastapi_hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.fastapi_hpa.targetCPUUtilizationPercentage }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.fastapi_service_clusterip.port }}
      targetPort: {{ .Values.fastapi_image.port}}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - secretName: {{ .Chart.Name }}-certificate
      hosts:
      - {{ .Values.fastapi_ingress.host }}
  rules:
  - host: {{ .Values.fastapi_ingress.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: {{ .Values.fastapi_ingress.port }}
