apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgadmin.name }}-secret
  namespace: {{ .Values.namespace }}
data:
  password: cm9vdA==

---

apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pgadmin.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.pgadmin.name }}
spec:
  containers:
  - name: {{ .Values.pgadmin.name }}
    image: dpage/pgadmin4
    ports:
      - containerPort: 80
        name: {{ .Values.pgadmin.name }}
    envFrom:
    - secretRef:
        name: {{ .Values.pgadmin.name }}-secret

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgadmin.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    name: {{ .Values.pgadmin.name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.pgadmin.port }}
    targetPort: {{ .Values.pgadmin.targetPort }}
    nodePort: {{ .Values.pgadmin.nodePort }}
