apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.name }}-{{ .Values.namespace }}-config
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: c3RvcmVkYg==
  POSTGRES_HOST_AUTH_METHOD: dHJ1c3Q=

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: {{ .Values.db.name }}-storage
          persistentVolumeClaim:
            claimName: {{ .Values.db.name }}-db-pvc
      containers:
        - name: db
          image: {{ .Values.db.image }}
          ports:
            - containerPort: {{ .Values.db.port }}
              name: db
          envFrom:
            - secretRef:
                name: {{ .Values.db.name }}-{{ .Values.namespace }}-config
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data/"
              name: {{ .Values.db.name }}-storage

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: db
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.name }}-helm-db-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/{{ .Values.namespace }}"
  storageClassName: {{ .Values.namespace }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.name }}-helm-db-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.namespace }}
  resources:
    requests:
      storage: 128Mi
