apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: standard
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t
  PGADMIN_DEFAULT_PASSWORD: cm9vdA==

---

apiVersion: v1
kind: Pod
metadata:
  name: pgadmin
  namespace: standard
  labels:
    name: pgadmin
spec:
  containers:
  - name: pgadmin
    image: dpage/pgadmin4
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        name: pgadmin
    envFrom:
    - secretRef:
        name: pgadmin-secret

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: standard
spec:
  type: NodePort
  selector:
    name: pgadmin
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
